spring:
  application:
    name: space-cats-market

  liquibase:
    change-log: classpath:db/changelog/changelog.xml
    enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true


application:
  greetings:
    cosmic-cat:
      name: cosmic-cat
      message: Hello from space cat ${application.greetings.cosmic-cat.name}
  payment-service:
    base-path: http://localhost:8089
    payments: ${application.payment-service.base-path}/payment-service/v1/payments
    timeout: 5000
  feature:
    toggles:
      galactic-products: true

---
spring:
  config:
    activate:
      on-profile: dev
application:
  feature:
    toggles:
      galactic-products: true
