spring:
  application:
    name: spacecats-market

  liquibase:
    change-log: classpath:db/changelog/changelog.xml
    enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

application:
  order-audit-service:
    base-path: http://localhost:8089
    orders: ${application.order-audit-service.base-path}/order-audit/v1/orders
    restclient:
      response-timeout: 1000
    timeout: 5000
  feature:
    toggles:
      galactic-products: true

