spring:
  profiles:
    active: local
  application:
    name: space-cats-market

application:
  greetings:
    cosmic-cat:
      name: cosmic-cat
      message: Hello from space cat ${application.greetings.cosmic-cat.name}
  payment-service:
    base-path: http://localhost:8089
    payments: ${application.payment-service.base-path}/payment-service/v1/payments
    timeout: 5000
  feature:
    toggles:
      galactic-products: true

---
spring:
  config:
    activate:
      on-profile: dev
application:
  feature:
    toggles:
      galactic-products: true
