openapi: 3.0.0
info:
  title: Spacecats Market API
  description: API for managing customers, products, and orders
  version: 1.0.0

paths:
  /api/v1/customers:
    get:
      summary: Get all customers
      tags:
        - Customers
      responses:
        '200':
          description: List of all customers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerDetailsListDto'
    post:
      summary: Create a new customer
      tags:
        - Customers
      requestBody:
        description: Customer data to create a new customer
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerDetailsDto'
      responses:
        '200':
          description: Customer created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerDetailsDto'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'

  /api/v1/customers/{id}:
    get:
      summary: Get customer by ID
      tags:
        - Customers
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID of the customer to retrieve
      responses:
        '200':
          description: Customer found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerDetailsDto'
        '404':
          description: Customer not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/products:
    get:
      summary: Get all products
      tags:
        - Products
      responses:
        '200':
          description: List of all products
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDtoList'
    post:
      summary: Create a new product
      tags:
        - Products
      requestBody:
        description: Product data to create a new product
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductDto'
      responses:
        '200':
          description: Product created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDto'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'

  /api/v1/products/{productId}:
    get:
      summary: Get product by ID
      tags:
        - Products
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
          description: ID of the product to retrieve
      responses:
        '200':
          description: Product found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDto'
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/{customerReference}/orders/{cartId}:
    post:
      summary: Place an order
      tags:
        - Orders
      parameters:
        - in: path
          name: customerReference
          required: true
          schema:
            type: string
          description: Customer reference for the order
        - in: path
          name: cartId
          required: true
          schema:
            type: string
          description: Cart ID for the order
      requestBody:
        description: Order data to place a new order
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlaceOrderRequestDto'
      responses:
        '200':
          description: Order placed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlaceOrderResponseDto'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'

components:
  schemas:
    CustomerDetailsDto:
      type: object
      properties:
        name:
          type: string
          maxLength: 100
          description: Name of the customer
        address:
          type: string
          maxLength: 255
          description: Address of the customer
        phoneNumber:
          type: string
          pattern: "^\\+?[0-9. ()-]{7,25}$"
          description: Phone number of the customer
        email:
          type: string
          format: email
          description: Email of the customer
        preferredChannel:
          type: array
          items:
            type: string
          description: Preferred communication channels

    CustomerDetailsListDto:
      type: object
      properties:
        customerDetailsEntries:
          type: array
          items:
            $ref: '#/components/schemas/CustomerDetailsEntry'

    CustomerDetailsEntry:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier of the customer
        name:
          type: string
          description: Name of the customer
        address:
          type: string
          description: Address of the customer
        phoneNumber:
          type: string
          description: Phone number of the customer
        email:
          type: string
          description: Email of the customer
        preferredChannel:
          type: array
          items:
            type: string
          description: Preferred communication channels

    ProductDto:
      type: object
      properties:
        name:
          type: string
          description: Name of the product
        price:
          type: number
          description: Price of the product
        description:
          type: string
          description: Description of the product

    ProductDtoList:
      type: object
      properties:
        products:
          type: array
          items:
            $ref: '#/components/schemas/ProductDto'

    PlaceOrderRequestDto:
      type: object
      properties:
        entries:
          type: array
          items:
            $ref: '#/components/schemas/OrderEntryDto'
        totalPrice:
          type: number
          description: Total price of the order

    PlaceOrderResponseDto:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier of the order
        status:
          type: string
          description: Status of the order

    OrderEntryDto:
      type: object
      properties:
        productType:
          type: string
          description: Type of the product
        amount:
          type: number
          description: Amount of the product

    ValidationError:
      type: object
      properties:
        status:
          type: string
          example: "400"
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ParamsViolationDetails'

    ErrorResponse:
      type: object
      properties:
        type:
          type: string
          description: URI reference identifying the error type
        title:
          type: string
          description: A short description of the error
        status:
          type: integer
          description: HTTP status code
        detail:
          type: string
          description: Detailed description of the error

    ParamsViolationDetails:
      type: object
      properties:
        fieldName:
          type: string
          description: Field where validation error occurred
        reason:
          type: string
          description: Reason for the validation error
